name: Lab6

on: push

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Deploy
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        env:
         username: 'ubuntu'
         server: '3.88.211.148'
         ssh_private_key: ${{ secrets.EC2_SSH_KEY}}
         local_path: './*'
         remote_path: '/var/www/html'
